name: Pull Request related comments
on:
  pull_request_target:
    types:
      - opened
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Opening Pull Request
        uses: wow-actions/auto-comment@v1
        with:
          github-token : ${{ secrets.APIVerse_SECRET }}
          pullRequestOpened: |
           @{{ author }}, Thank you for creating PR! We will review it super soon. 😇❣️
           As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
           We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
           Thank you for being an essential part of our community. Together, we'll keep building amazing things!
           Don’t forget to ⭐ our repository!
           Happy Coding!✨
           Will See you soon❣️


